packageExtensions:
  chalk@*:
    dependencies:
      "#ansi-styles": npm:ansi-styles@*
      "#supports-color": npm:supports-color@*

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
